- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    npm_packages:
      - grunt-cli
      - gulp
      - bower
      # - browserify
      # - babel
      # - coffee-script
      - static-server
      - init-package-json-parcel
      # - hexo-cli
      # - karma
      # - typescript
      # - tsd
      # - dtsm
      # - tslint
      # - yo
    atom_packages_packages:
      - project-manager
      - open-recent
      - autocomplete-plus
      - file-icons
      - markdown-writer
      - autoclose-html
      - editorconfig
      - japan-util
      - symbols-tree-view
      - quick-highlight
      - show-ideographic-space
      - git-plus
      - atom-beautify
      - atom-typescript
      - linter
      - git-time-machine
      - git-diff-details
      - git-blame
      # - linter-tslint
      - emmet
      - tablr
      #   - japanese-wrap
    gem_packages:
      - { name: sass }
      - { name: compass }
      # - { name: animation }
      - { name: ceaser-easing }

  tasks:
    # node
    - name: node stable をインストール
      shell: nodebrew selfupdate; nodebrew install-binary v8.x; nodebrew use v8.x
      # when node|failed
    - name: npm package をインストール
      npm: name={{item}} global=yes
      with_items: npm_packages
    # gem
    - name: gem package をインストール
      gem: name={{item.name}}
      with_items: gem_packages
    - name: gem package をインストール2
      shell: sudo gem install animation --pre

  roles:
    - hnakamur.atom-packages
