- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    npm_packages:
      - grunt-cli
      - gulp
      - bower
      - coffee-script
      - karma
      - browserify
      - typescript
      - babel
    atom_packages_packages:
      - japanese-wrap
      - project-manager
      - open-recent
      - autocomplete-plus
      - file-icons
      - minimap
      - markdown-writer
      - autoclose-html
      - editorconfig
      - japan-util
      - symbols-tree-view
      - quick-highlight
      - show-ideographic-space
      - git-plus
    gem_packages:
      - { name: sass }
      - { name: compass }
      # - { name: animation }
      - { name: ceaser-easing }

  tasks:
    # node
    - name: node stable をインストール
      shell: nodebrew selfupdate; nodebrew install-binary stable; nodebrew use stable
      # when node|failed
    - name: npm package をインストール
      npm: name={{item}} global=yes
      with_items: npm_packages
    # gem
    - name: gem package をインストール
      gem: name={{item.name}}
      with_items: gem_packages
    - name: gem package をインストール2
      shell: sudo gem install animation --pre

  roles:
    - hnakamur.atom-packages
